os: linux
language: java
dist: trusty
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
branches:
  only:
    - master
    - /^v.*$/

script:
  - mvn test
  - mvn package